### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by shacea** [cmubig/Frida#11]
ANTIALIAS was removed in Pillow 10.0.0. 
ANTIALIAS has to be replaced by PIL.Image.LANCZOS or PIL.Image.Resampling.LANCZOS.

or

Use Pillow==9.5.0 instead.
I used Pillow==9.5.0 and problem solved.

**Comment by pschaldenbrand** [comment]
Thank you! Updated main branch to have this change: https://github.com/cmubig/Frida/commit/9829ac6f29ba63f801f7f6fb01a6eee37588e89b
